openapi: 3.0.3
info:
  title: Vue-Springboot-Memo Api
  description: |-
      Vue Springboot client와 server 테스트
      https://github.com/doyou1/vue-spring-sampling
  version: 1.0.0
servers:
  - url: http://Aws-jh-env.eba-ppbenvkp.ap-northeast-1.elasticbeanstalk.com/api
tags:
  - name: /api/memo
    description: about memo
paths:
  /api/memo:
    get:
      tags:
        - /api/memo
      summary: get memo list
      description: get memo list
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Memo'     
    post:
      tags:
        - /api/memo
      summary: add a Memo item
      description: add a Memo item
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
  /api/memo/{id}:
    put:
      tags:
        - /api/memo
      summary: update a Memo item
      description: update a Memo item
      parameters:
        - name: id
          in: path
          required: true
          description: id to update the Memo item
          schema:
            type : integer
            format: int64
            example: 10
      requestBody:
        required: true
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/Memo'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
components:
  schemas:
    Memo:
      properties:
        id:
          type: integer
          format: int64
          example: 10
        content:
          type: string
          example: memo content
        isDone:
          type: boolean
    ApiResponse:
      type: object
      properties:
        id:
          type: integer
          format: int32
          example: 10
        isSuccess:
          type: boolean